name: Update dataframe from cameras

on:
  push:
    branches:
      - master

  schedule: # every hour
    - cron:  '* * * * *'

jobs:
  execute_main:
    runs-on: ubuntu-latest


    steps: #TODO: find right path for export CORONA=''
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r ./requirements.txt
            export CORONA=$(pwd)
            echo $CORONA
      - name: Execute test.py
        run: |
            export CORONA=$(pwd)
            python ./src/test.py  
            
      - name: Commit files 
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git add ./data/test.txt
            git commit -m "Update dataframe"
      - name: Push to repo
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
